services:
  mongo:
    container_name: mongodb
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--requirepass", "123"]
    ports:
      - "6379:6379"

volumes:
  mongo-data:
