spring:
  application:
    name: basket-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: basket_service
      username: leozinho
      password: 123
    redis:
      host: localhost
      port: 6379
      password: 123

  cache:
    redis:
      time-to-live: 60000