spring:
  application:
    name: basket-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: basket_service

    redis:
      host: localhost
      port: 6379
      password: 123

  cache:
    redis:
      time-to-live: 60000

basket:
  client:
    platzi: "https://api.escuelajs.co/api/v1"
